---
# Cantaloupe version
cantaloupe_version: 4.1
# Where to extract the cantaloupe archive
cantaloupe_install_root: /opt
# Target of a symlink from the extracted cantaloupe archive 
cantaloupe_symlink: /opt/cantaloupe
# Path to cantaloupe logs
cantaloupe_log_path: /var/log/cantaloupe
# Cantaloupe user
cantaloupe_user: vagrant
# Cantaloupe group
cantaloupe_group: vagrant

# Whether to automatically deploy the war file
cantaloupe_deploy_war: yes
# Where to deploy the war to
cantaloupe_deploy_war_path: /var/lib/tomcat8/webapps
# Name for the deployed war (minus .war), this is the context path
cantaloupe_deploy_war_filename: cantaloupe
# Create the filesystem cache directory automatically
cantaloupe_create_FilesystemCache_dir: no


