---

mongodb_package: mongodb
mongodb_version: "3.6"

mongodb_security_authorization: "enabled"

mongodb_user_admin_name: "siteUserAdmin"
mongodb_user_admin_password: "passw0rd"

mongodb_root_admin_name: "siteRootAdmin"
mongodb_root_admin_password: "passw0rd"

mongodb_root_backup_name: "backupuser"
mongodb_root_backup_password: "passw0rd"

mongodb_users:
  - {
      name: "datahub",
      password: "datahub",
      roles: "dbAdmin",
      database: "admin"
    }
  - {
      name: "imagehub",
      password: "imagehub",
      roles: "dbAdmin",
      database: "admin"
    }

