---
# Cantaloupe version
cantaloupe_version: 4.1
# Where to extract the cantaloupe archive
cantaloupe_install_root: /opt
# Target of a symlink from the extracted cantaloupe archive 
cantaloupe_symlink: /opt/cantaloupe
# Path to cantaloupe logs
cantaloupe_log_path: /var/log/cantaloupe
# Cantaloupe user
cantaloupe_user: vkcuser
# Cantaloupe group
cantaloupe_group: vkcuser

# Whether to automatically deploy the war file
cantaloupe_deploy_war: yes
# Where to deploy the war to
cantaloupe_deploy_war_path: /var/lib/tomcat8/webapps
# Name for the deployed war (minus .war), this is the context path
cantaloupe_deploy_war_filename: ROOT
# Create the filesystem cache directory automatically
cantaloupe_create_FilesystemCache_dir: no

# Built-in processors are `Java2dProcessor`, `GraphicsMagickProcessor`,
# `ImageMagickProcessor`, `TurboJpegProcessor`, `KakaduNativeProcessor`,
# `KakaduDemoProcessor`, `OpenJpegProcessor`, `JaiProcessor`,
# `PdfBoxProcessor`, and `FfmpegProcessor`.
# Some of these have third-party dependencies and won't work out-of-the-box.
cantaloupe_processor_ManualSelectionStrategy_tif : ImageMagickProcessor

# preserve image metadata
cantaloupe_processor_metadata_preserve : "true"

# Server-side path that will be prefixed to the identifier in the URL.
# Trailing slash is important!
cantaloupe_FilesystemSource_BasicLookupStrategy_path_prefix : /home/vkcuser/images/